services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=sqlite
      - DEBUG=True
      - SECRET_KEY=django-insecure-change-this-in-real-deployments
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=https://*.iximiuz.com
    volumes:
      - sqlite_data:/app/data
      - media_data:/app/media

volumes:
  sqlite_data:
  media_data: